### ISSUE TITLE
Compile examples based on AmberMini version?

### ISSUE THREAD

**Issue by Lnaden** [choderalab/yank-examples#13]
With AmberMini v16, there are a number of FF files which got moved into a folder called "oldff/leaprc.{file}". A number of our examples make use of some of these files and expect them in the standard folder for leaprc files. Should we have yank-examples do a check of which AmberMini is installed and modify the examples based on the version of AmberMini, or should we assume a specific version of AmberMini?

Can't exactly test right now since AmberMini 16 hasnt been merged yet, active discussion and all

**Comment by jchodera** [comment]
Like OpenMM, we may want to push people toward newer forcefields, so we may want to require people specify `oldff/leaprc.{file}` in order to access the older forcefields. This will only work if we require `ambertools 16` for `yank 1.0`, though, but I think this is the plan.

**Comment by Lnaden** [comment]
Putting a pin in this until we resolve the AmberMini v16 PR

**Comment by Lnaden** [comment]
Closing this issue, related to a different one i'll open
