### ISSUE TITLE
Add Zeonodo DOI integration

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank-examples#19]
We should add [Zenodo DOI integration](https://guides.github.com/activities/citable-code/) so this repo gets assigned a DOI when we cut a release.

**Comment by Lnaden** [comment]
@jchodera do you have the id for this repo, or do we have to cut a first release before we can tie automatic identifier to this?

**Comment by jchodera** [comment]
I'll enable zenodo for this. No DOI gets assigned until the first release.

**Comment by Lnaden** [comment]
Okay, once you have the link let me know, I have the placeholder link in my current PR I can put it in

**Comment by jchodera** [comment]
Looks like we don't know the badge URL until we cut a first release. Maybe the first release can be `0.1.0` or something, then I can provide you with the badge URL to add to the `README.md`.
