### ISSUE TITLE
Testing / automating examples

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank-examples#25]
What do you think about adding a script to run all the examples automatically on the cluster? It could simply submit all of the `run-torque.sh` scripts for each example, but it would be a useful way for us to check out this project and run everything to make sure it works.

**Comment by Lnaden** [comment]
I think thats a good idea that I wanted to put in as well. I have tested these individually to ensure they at least run by hand. I think as a "1.0" release we just wanted to get good example files out there and the [corresponding documentation](https://github.com/choderalab/yank/pull/543) with walkthrough.

**Comment by Lnaden** [comment]
Fixed by #33
