### ISSUE TITLE
Avoid using `setup/` subdirectory in examples

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank-examples#29]
@andrrizzi : Doesn't `yank` automatically create `setup/` subdirectories that contain the built systems? If so, we should avoid having our input files in `setup/` subdirectories at the outset, since it makes it very difficult to clean up failed runs to restart them.

I believe other examples used an `input/` directory so that `setup` and `molecules` could be purged to start over after a failed run.

**Comment by jchodera** [comment]
Actually, the output seems to go into `output/` now, so no issue here.

**Comment by andrrizzi** [comment]
> Doesn't `yank` automatically create setup/ subdirectories

It does and, although not critical, it may be a good idea to keep it in an `input/` folder in case the user decides to tinker with the YAML file. Reopening but feel free to close if this turns out to be a non-issue.

**Comment by Lnaden** [comment]
Im working through a batch of open issues in a pr, im renaming all source file dirs to `input`
