### ISSUE TITLE
softcore_beta and parameters in examples

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank-examples#34]
I've noticed that many example don't specify in the options `softcore_beta: 0.0`, should we add it in all of them? Does it make sense to change the default value of that parameter in `AbsoluteAlchemicalFactory` to be `0.0` instead of `1.0`?

Also in many example the `gaff` or `ff14sb` forcefields are specified both in the `molecule` and in the `system`, but this is not necessary.

**Comment by jchodera** [comment]
> I've noticed that many example don't specify in the options softcore_beta: 0.0, should we add it in all of them? Does it make sense to change the default value of that parameter in AbsoluteAlchemicalFactory to be 0.0 instead of 1.0?

Good idea---let's change the default in `alchemy` to disable alchemical softcore for charges (beta = 0.0) and remove that from the examples.

> Also in many example the gaff or ff14sb forcefields are specified both in the molecule and in the system, but this is not necessary.

Let's fix that too!

**Comment by jchodera** [comment]
Let me know if you want me to make the change to `alchemy`.
