### ISSUE TITLE
Update conda recipe to latest yank version

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/yank-examples#45]
I'm trying to install on my laptop (OS X) and am getting a "package not found" error when I attempt to `conda install -c omnia yank-examples`.

**Comment by jchodera** [comment]
We're waiting to add the `yank-examples` package because it will depend on the YANK preview release package, which hasn't been cut yet.

We're debugging some issues with the Boresch restraint standard state correction:
https://github.com/choderalab/yank/issues/553

**Comment by davidlmobley** [comment]
OK, that's fine. Just, er, all of the docs I was reading say to install it that way, so it's perplexing to not have it work. (I cloned the repo instead.)

**Comment by jchodera** [comment]
We're very nearly there. We had intended to have this out last week before we ran into `nan` problems and the Boresch restraint issue.

**Comment by jchodera** [comment]
I've updated the name of this issue to reflect the fact that the current `yank-examples` recipe [refers to an outdated release of YANK](https://github.com/omnia-md/conda-recipes/blob/master/yank-examples/meta.yaml#L15-L20).

**Comment by Lnaden** [comment]
I don't think the examples use any features from 0.18.0, so the minimum version of 0.17.0 should be fine, no?

**Comment by jchodera** [comment]
Hm, I thought there were some critical bugfixes in 0.18.0, but I guess not if we don't use `auto`.
