### ISSUE TITLE
Question on implicit solvent example

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/yank-examples#47]
Why does the phenol/implicit solvent hydration example use multiple lambda values? I thought John had told me the typical protocol you guys were using used only a single gas phase simulation and reprocessed in implicit solvent. but this is running multiple lambda values and lambda exchange, if I understand correctly.

**Comment by jchodera** [comment]
> Why does the phenol/implicit solvent hydration example use multiple lambda values? I thought John had told me the typical protocol you guys were using used only a single gas phase simulation and reprocessed in implicit solvent. but this is running multiple lambda values and lambda exchange, if I understand correctly.

Our current YANK example uses multiple lambda values, and we have not optimized that at all.

The GBFF project uses a single vacuum state simulation and just does reweighting:
https://github.com/choderalab/gbff

You can probably aggressively trim down the number of replicas to 1-2 states for the YANK example, but we have not yet done that.

**Comment by davidlmobley** [comment]
Thanks.
