### ISSUE TITLE
Examples don't give appropriate precision/sig figs

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/yank-examples#48]
I ran the phenol implicit solvent hydration example, and end up getting final answers out like `Free energy of solvation:          -10.016 +- 0.000 kT`. You'll need to adjust to use appropriate significant figures and uncertainty handling.

**Comment by jchodera** [comment]
Can you post this in the http://github.com/choderalab/yank issue tracker? The files in here are just inputs, but this is requesting a code change!
