### ISSUE TITLE
Phenol explicit water example error

### ISSUE THREAD

**Issue by nividic** [choderalab/yank-examples#49]
Hi there I was trying the phenol explicit water example but it was giving me errors. I tried on a clean installation of conda on different systems: Ubuntu 14.04, Scientific Linux and OSX Sierra and the issue was the same.  If I run the command:

yank script --yaml=explicit.yaml

in the phenol directory I got the error:

File "/home/gac/local/anaconda/lib/python2.7/site-packages/yank/utils.py", line 1599, in run
    raise RuntimeError(error_msg + ' Check log file {}'.format(log_path))
RuntimeError: Argument #2 is type String must be of type: [unit] Check log file /home/gac/disk/TEST/Mobley/yank-examples/examples/hydration/phenol/setup/systems/hydration-system/solvent1.leap.log

I was able to track down the problem which is in the explicit.yaml file. I had to change 

    leap:
      parameters: [leaprc.gaff, leaprc.protein.ff14SB]
in

   leap:
      parameters: [leaprc.gaff, oldff/leaprc.ff99SBildn]
   
The problem seems to be that the unit TIP3PBOX required by tleap is not loaded in leaprc.protein.ff14SB and therefore yank is not able to solvate the system. Please let me know if you need further info

Gaetano

**Comment by andrrizzi** [comment]
Thanks for catching this! @Lnaden might know more about this, but I think you can also substitute `leaprc.protein.ff14SB` to `oldff/leaprc.ff14SB`, which should be the exact same force field, only in contains also the parameters for TIP3P water molecules. That old file has been broken up into different files with the new antechamber release.

**Comment by Lnaden** [comment]
I did not notice that the changed leaprc files changed how waters were loaded as well. I just merged #50 which should address the issue. Give it a try to make sure though before we close this issue

**Comment by nividic** [comment]
I tried on Sierra OSX and Ubuntu and it seems to correctly work now. Thanks for your prompt help
Gaetano

**Comment by Lnaden** [comment]
Great to hear!
