### ISSUE TITLE
Turn on pack for binding examples and smiles ligands

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank-examples#52]
I just noticed that in our binding examples with ligands generated from smiles the `pack` option is off. I’ll open a PR to fix it.

**Comment by andrrizzi** [comment]
Ah! Sorry, the option was already on. It was just the yank docs reported the incorrect default.

**Comment by jchodera** [comment]
Is it really on by default? The CK2 example had the ligand start far away.

**Comment by andrrizzi** [comment]
It is `off` by default, but the docs reported it `on`. I just didn't see the `pack` option specified the first time I looked at the example YAML script.

**Comment by jchodera** [comment]
Ah! Thanks!

**Comment by jchodera** [comment]
So we should definitely turn that on in the examples that use Harmonic or FlatBottom restraints.
