### ISSUE TITLE
Cut release

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank-examples#53]
Are we ready to go here?

**Comment by jchodera** [comment]
What should the release number be? 0.14.0 to match the major.minor numbers of the corresponding `yank` release?

**Comment by Lnaden** [comment]
Last I had checked last night, yank was not searchable through conda, it is this morning. I think the examples should be numbered independent of the main yank release and start at 1.0.0 so they can develop on their own, we just say which version of yank a given release is tied to.

**Comment by Lnaden** [comment]
Release 1.0.0 cut!
