### ISSUE TITLE
NAN encountered in freesolv example.

### ISSUE THREAD

**Issue by kexul** [choderalab/yank-examples#87]
Hi, I clone the freesolv example code and run it in my local machine with the error as follow: 

```
2020-03-29 21:35:49,958: CRITICAL - openmmtools.multistate.multistatesampler - NaN encountered in unsampled thermodynamic state energies for the following replicas and states
        Energies for positions at replica 0 (current state 18): [-25905.54804438             nan] kT
2020-03-29 21:35:49,962: CRITICAL - yank.experiment -

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!     CRITICAL: Experiment NaN    !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
The following experiment threw a NaN! It should NOT be considered!
Experiment: sams/experiments/sparseprotocol_3
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2020-03-29 21:35:49,962: Single node: executing <bound method MultiStateReporter.close of <openmmtools.multistate.multistatereporter.MultiStateReporter object at 0x7f7b89ec99d0>>
```

I used the same config except an modification in the molecule param , because I don't have an openeye license.
The modified part is as follow:
```
molecules:
  freesolv:
    filepath: mobley_1723043.mol2
    antechamber:
      charge_method: bcc
```
Any help is appreciated!

**Comment by kexul** [comment]
I tried change the `alchemical path` to `auto`, the same error raised.

**Comment by andrrizzi** [comment]
Could you post the full yaml file you are using and attach/link the input molecule?

**Comment by andrrizzi** [comment]
Also, please post the full log.

**Comment by kexul** [comment]
Here is my files: 

[files.zip](https://github.com/choderalab/yank-examples/files/4404433/files.zip)
Thank you @andrrizzi !

You may noticed that I changed the splitting in mcmc_moves too. It seems like the old syntax is not supported now.

**Comment by kexul** [comment]
Any tips? @andrrizzi

**Comment by andrrizzi** [comment]
Hi @kexul . From the logs, it looks like the calculation in implicit solvent works fine and you have problems with the one in explicit solvent. I'd try reducing the timestep from 4fs to 3fs (or even 2fs) and see if the integration is more stable.

**Comment by kexul** [comment]
That worked! Thank you so much! @andrrizzi
